local Parser = require "...libs.parser"
local ErrLoc = require "...libs.errloc"

-- NOTE: Passing Tests
do
  local content = [[
record X {
  name: string
}
]]

  local new_parser_res = Parser.new("record_type", content)
  assert(new_parser_res:is_ok())

  local parser = new_parser_res:get_ok()

  local parser_res = parser:parse()
  assert(parser_res:is_ok())

  local ast = parser_res:get_ok()

  local expected = [[
AST
  TYPE X{
    ID_DECL -> name: TYPE string{
      ID_DECL -> data: TYPE *[0]u8
      ID_DECL -> size: TYPE u64
    }
  }
]]
  local res = ast:tostring()
  assert(expected == res)
end

do
  local content = [[
record X {
  name: string
}

Y : <const> = X
]]

  local new_parser_res = Parser.new("id_decl_record_type", content)
  assert(new_parser_res:is_ok())

  local parser = new_parser_res:get_ok()

  local parser_res = parser:parse()
  assert(parser_res:is_ok())

  local ast = parser_res:get_ok()

  local expected = [[
AST
  TYPE X{
    ID_DECL -> name: TYPE string{
      ID_DECL -> data: TYPE *[0]u8
      ID_DECL -> size: TYPE u64
    }
  }
  ID_DECL -> Y: TYPE X{
    ID_DECL -> name: TYPE string{
      ID_DECL -> data: TYPE *[0]u8
      ID_DECL -> size: TYPE u64
    }
  } = ID -> X: TYPE X{
      ID_DECL -> name: TYPE string{
        ID_DECL -> data: TYPE *[0]u8
        ID_DECL -> size: TYPE u64
      }
    }
]]
  local res = ast:tostring()
  assert(expected == res)
end

do
  local content = [[
s := "hello world"

print(s.size)
]]

  local new_parser_res = Parser.new("rec_field_access", content)
  assert(new_parser_res:is_ok())

  local parser = new_parser_res:get_ok()

  local parser_res = parser:parse()
  assert(parser_res:is_ok())

  local ast = parser_res:get_ok()

  local expected = [[
AST
  ID_DECL -> s: TYPE string{
    ID_DECL -> data: TYPE *[0]u8
    ID_DECL -> size: TYPE u64
  } = LITERAL("hello world")
  PROC_CALL print(
    FIELD -> s.size: TYPE u64
  )
]]
  local res = ast:tostring()
  assert(expected == res)
end

-- NOTE: Failing Tests
